[2025-04-18T06:43:42.148+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T06:43:42.176+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: image_processing_pipeline.check_for_new_images manual__2025-04-18T06:43:41.156596+00:00 [queued]>
[2025-04-18T06:43:42.190+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: image_processing_pipeline.check_for_new_images manual__2025-04-18T06:43:41.156596+00:00 [queued]>
[2025-04-18T06:43:42.191+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-18T06:43:42.212+0000] {taskinstance.py:2890} INFO - Executing <Task(S3KeySensor): check_for_new_images> on 2025-04-18 06:43:41.156596+00:00
[2025-04-18T06:43:42.223+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'image_processing_pipeline', 'check_for_new_images', 'manual__2025-04-18T06:43:41.156596+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/image_processing_dag.py', '--cfg-path', '/tmp/tmp937xnoyb']
[2025-04-18T06:43:42.225+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask check_for_new_images
[2025-04-18T06:43:42.226+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T06:43:42.226+0000] {standard_task_runner.py:72} INFO - Started process 198 to run task
[2025-04-18T06:43:42.276+0000] {task_command.py:467} INFO - Running <TaskInstance: image_processing_pipeline.check_for_new_images manual__2025-04-18T06:43:41.156596+00:00 [running]> on host 96ec7c07bc54
[2025-04-18T06:43:42.390+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='image_processing_pipeline' AIRFLOW_CTX_TASK_ID='check_for_new_images' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T06:43:41.156596+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T06:43:41.156596+00:00'
[2025-04-18T06:43:42.391+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T06:43:42.408+0000] {baseoperator.py:423} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-04-18T06:43:42.408+0000] {s3.py:114} INFO - Poking for key : s3://original-images-***/*.jpg
[2025-04-18T06:43:42.422+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-04-18T06:43:42.423+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-04-18T06:43:43.175+0000] {base.py:339} INFO - Success criteria met. Exiting.
[2025-04-18T06:43:43.190+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T06:43:43.191+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=image_processing_pipeline, task_id=check_for_new_images, run_id=manual__2025-04-18T06:43:41.156596+00:00, execution_date=20250418T064341, start_date=20250418T064342, end_date=20250418T064343
[2025-04-18T06:43:43.243+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T06:43:43.276+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-18T06:43:43.278+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
